### ISSUE TITLE
Latest version (1.3.5) server not working

### ISSUE THREAD

**Issue by DavidBarishev** [chippledipple/stella-octangula#6]
Hey,
We made a server using the latest version (1.3.5) bot client and server.
When we tried to log in, we faced an error: 
![javaw_2017-09-12_16-03-04](https://user-images.githubusercontent.com/13189425/30327529-0f0f6bfc-97d5-11e7-8d6b-0d1a832bd99f.png)
We fixed this by copying the client's mods that were missing (reborn and harvestcraft), to the server mods, and it fixed the problem.

**Comment by chippledipple** [comment]
Thanks for reporting this. The bug has been fixed.
